% BUILDWINDOWS  Script for compiled mex interface to Darwin for Windows
% Stephen Gould <stephen.gould@anu.edu.au>

% check that Darwin libraries have been compiled
if (~exist('..\..\bin\drwnBase.lib') || ~exist('..\..\bin\drwnIO.lib') || ...
    ~exist('..\..\bin\drwnML.lib') || ~exist('..\..\bin\drwnPGM.lib')),
    error('YOU NEED TO COMPILE THE DARWIN LIBRARIES FIRST (IN RELEASE MODE)');
end;

% compile test application
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexDarwinTest.cpp

% compile machine learning applications
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexLearnClassifier.cpp
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexEvalClassifier.cpp
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexAnalyseClassifier.cpp
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexKMeans.cpp
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexGetLinearTransform.cpp
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexSetLinearTransform.cpp

% build graphical models applications
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexFactorGraphInference.cpp
mex -I..\..\external\eigen3 -I..\..\include -L..\..\bin -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexMaxFlow.cpp

% build vision applications
if (exist('..\..\external\opencv', 'dir')),
    if (strcmp(mexext, 'mexw64')),
        mex -I..\..\external\eigen3 -I..\..\include ...
            -I..\..\external\opencv\build\include -I..\..\external\opencv\build\include\opencv ...
            -L..\..\bin -L..\..\external\opencv\build\x64\vc10\lib ...
            -lopencv_imgproc246 -lopencv_core246 -lopencv_ml246 -lopencv_highgui246 ...
            -ldrwnVision -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexImageCRF.cpp

        mex -I..\..\external\eigen3 -I..\..\include ...
            -I..\..\external\opencv\build\include -I..\..\external\opencv\build\include\opencv ...
            -L..\..\bin -L..\..\external\opencv\build\x64\vc10\lib ...
            -lopencv_imgproc246 -lopencv_core246 -lopencv_ml246 -lopencv_highgui246 ...
            -ldrwnVision -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexLoadSuperpixels.cpp
    else
        mex -I..\..\external\eigen3 -I..\..\include ...
            -I..\..\external\opencv\build\include -I..\..\external\opencv\build\include\opencv ...
            -L..\..\bin -L..\..\external\opencv\build\x86\vc10\lib ...
            -lopencv_imgproc246 -lopencv_core246 -lopencv_ml246 -lopencv_highgui246 ...
            -ldrwnVision -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexImageCRF.cpp

        mex -I..\..\external\eigen3 -I..\..\include ...
            -I..\..\external\opencv\build\include -I..\..\external\opencv\build\include\opencv ...
            -L..\..\bin -L..\..\external\opencv\build\x86\vc10\lib ...
            -lopencv_imgproc246 -lopencv_core246 -lopencv_ml246 -lopencv_highgui246 ...
            -ldrwnVision -ldrwnPGM -ldrwnML -ldrwnIO -ldrwnBase mexLoadSuperpixels.cpp
    end
end
