# DARWIN PROJECT MAKEFILE
# Stephen Gould <stephen.gould@anu.edu.au>

.PHONY: clean

clean:
	cd helloworld && make clean && cd .. || true
	cd base && make clean && cd .. || true
	cd ml && make clean && cd .. || true
	cd pgm && make clean && cd .. || true
